using System.Collections.Generic;

namespace KBZ.Utils.Models
{
    public static class TimezoneAndCountry
    {
        private static List<KeyValuePair<string, string>> _timezoneAndCountryList;

        public static List<KeyValuePair<string, string>> TimezoneAndCountryList
        {
            get
            {
                _timezoneAndCountryList = new List<KeyValuePair<string, string>>
                {
                    new KeyValuePair<string, string>("Dateline Standard Time","US"),
                new KeyValuePair<string, string>("UTC-11","US"),
                new KeyValuePair<string, string>("Hawaiian Standard Time","US"),
                new KeyValuePair<string, string>("Alaskan Standard Time","US"),
                new KeyValuePair<string, string>("Pacific Standard Time (Mexico)","US"),
                new KeyValuePair<string, string>("Pacific Standard Time","US"),
                new KeyValuePair<string, string>("US Mountain Standard Time","US"),
                new KeyValuePair<string, string>("Mountain Standard Time (Mexico)","US"),
                new KeyValuePair<string, string>("Mountain Standard Time","US"),
                new KeyValuePair<string, string>("Central America Standard Time","US"),
                new KeyValuePair<string, string>("Central Standard Time","US"),
                new KeyValuePair<string, string>("Central Standard Time (Mexico)","MX"),
                new KeyValuePair<string, string>("Canada Central Standard Time","CA"),
                new KeyValuePair<string, string>("SA Pacific Standard Time",""),
                new KeyValuePair<string, string>("Eastern Standard Time","US"),
                new KeyValuePair<string, string>("US Eastern Standard Time","US"),
                new KeyValuePair<string, string>("Venezuela Standard Time","US"),
                new KeyValuePair<string, string>("Paraguay Standard Time",""),
                new KeyValuePair<string, string>("Atlantic Standard Time","CA"),
                new KeyValuePair<string, string>("Central Brazilian Standard Time","US"),
                new KeyValuePair<string, string>("SA Western Standard Time","BR"),
                new KeyValuePair<string, string>("Pacific SA Standard Time","FK"),
                new KeyValuePair<string, string>("Newfoundland Standard Time","VE"),
                new KeyValuePair<string, string>("E. South America Standard Time","BR"),
                new KeyValuePair<string, string>("Argentina Standard Time","AR"),
                new KeyValuePair<string, string>("SA Eastern Standard Time","GF"),
                new KeyValuePair<string, string>("Greenland Standard Time","GL"),
                new KeyValuePair<string, string>("Montevideo Standard Time","UY"),
                new KeyValuePair<string, string>("Bahia Standard Time","BR"),
                new KeyValuePair<string, string>("UTC-02",""),
                new KeyValuePair<string, string>("Mid-Atlantic Standard Time","BR"),
                new KeyValuePair<string, string>("Azores Standard Time","GL"),
                new KeyValuePair<string, string>("Cape Verde Standard Time","CV"),
                new KeyValuePair<string, string>("Morocco Standard Time","MA"),
                new KeyValuePair<string, string>("UTC",""),
                new KeyValuePair<string, string>("GMT Standard Time","GB"),
                new KeyValuePair<string, string>("Greenwich Standard Time","GB"),
                new KeyValuePair<string, string>("W. Europe Standard Time","FO"),
                new KeyValuePair<string, string>("Central Europe Standard Time","BE"),
                new KeyValuePair<string, string>("Romance Standard Time","UK"),
                new KeyValuePair<string, string>("Central European Standard Time","UK"),
                new KeyValuePair<string, string>("W. Central Africa Standard Time","CF"),
                new KeyValuePair<string, string>("Namibia Standard Time","KE"),
                new KeyValuePair<string, string>("Jordan Standard Time","JO"),
                new KeyValuePair<string, string>("GTB Standard Time","GR"),
                new KeyValuePair<string, string>("Middle East Standard Time","LB"),
                new KeyValuePair<string, string>("Egypt Standard Time","EG"),
                new KeyValuePair<string, string>("Syria Standard Time","SY"),
                new KeyValuePair<string, string>("E. Europe Standard Time","BY"),
                new KeyValuePair<string, string>("South Africa Standard Time","ZW"),
                new KeyValuePair<string, string>("FLE Standard Time",""),
                new KeyValuePair<string, string>("Turkey Standard Time","TR"),
                new KeyValuePair<string, string>("Israel Standard Time","IL"),
                new KeyValuePair<string, string>("Kaliningrad Standard Time",""),
                new KeyValuePair<string, string>("Libya Standard Time","LY"),
                new KeyValuePair<string, string>("Arabic Standard Time","YE"),
                new KeyValuePair<string, string>("Arab Standard Time","SA"),
                new KeyValuePair<string, string>("Belarus Standard Time","BY"),
                new KeyValuePair<string, string>("Russian Standard Time","RU"),
                new KeyValuePair<string, string>("E. Africa Standard Time","AQ"),
                new KeyValuePair<string, string>("Iran Standard Time","IR"),
                new KeyValuePair<string, string>("Arabian Standard Time","SA"),
                new KeyValuePair<string, string>("Azerbaijan Standard Time","AZ"),
                new KeyValuePair<string, string>("Russia Time Zone 3","RU"),
                new KeyValuePair<string, string>("Mauritius Standard Time","MU"),
                new KeyValuePair<string, string>("Georgian Standard Time","GE"),
                new KeyValuePair<string, string>("Caucasus Standard Time","AM"),
                new KeyValuePair<string, string>("Afghanistan Standard Time","AF"),
                new KeyValuePair<string, string>("West Asia Standard Time","TJ"),
                new KeyValuePair<string, string>("Ekaterinburg Standard Time","KZ"),
                new KeyValuePair<string, string>("Pakistan Standard Time","PK"),
                new KeyValuePair<string, string>("India Standard Time","IN"),
                new KeyValuePair<string, string>("Sri Lanka Standard Time","LK"),
                new KeyValuePair<string, string>("Nepal Standard Time","NP"),
                new KeyValuePair<string, string>("Central Asia Standard Time","KG"),
                new KeyValuePair<string, string>("Bangladesh Standard Time","BD"),
                new KeyValuePair<string, string>("N. Central Asia Standard Time","BD"),
                new KeyValuePair<string, string>("Myanmar Standard Time","MM"),
                new KeyValuePair<string, string>("SE Asia Standard Time","TH"),
                new KeyValuePair<string, string>("North Asia Standard Time","RU"),
                new KeyValuePair<string, string>("China Standard Time","CN"),
                new KeyValuePair<string, string>("North Asia East Standard Time","BN"),
                new KeyValuePair<string, string>("Singapore Standard Time","SG"),
                new KeyValuePair<string, string>("W. Australia Standard Time","AU"),
                new KeyValuePair<string, string>("Taipei Standard Time","TW"),
                new KeyValuePair<string, string>("Ulaanbaatar Standard Time","MN"),
                new KeyValuePair<string, string>("Tokyo Standard Time","PW"),
                new KeyValuePair<string, string>("Korea Standard Time","TL"),
                new KeyValuePair<string, string>("Yakutsk Standard Time","MN"),
                new KeyValuePair<string, string>("Cen. Australia Standard Time","AU"),
                new KeyValuePair<string, string>("AUS Central Standard Time","AU"),
                new KeyValuePair<string, string>("E. Australia Standard Time","AU"),
                new KeyValuePair<string, string>("AUS Eastern Standard Time","AU"),
                new KeyValuePair<string, string>("West Pacific Standard Time","GU"),
                new KeyValuePair<string, string>("Tasmania Standard Time","AU"),
                new KeyValuePair<string, string>("Magadan Standard Time","RU"),
                new KeyValuePair<string, string>("Vladivostok Standard Time","RU"),
                new KeyValuePair<string, string>("Russia Time Zone 10","RU"),
                new KeyValuePair<string, string>("Central Pacific Standard Time","AU"),
                new KeyValuePair<string, string>("Russia Time Zone 11","RU"),
                new KeyValuePair<string, string>("New Zealand Standard Time","NZ"),
                new KeyValuePair<string, string>("UTC+12",""),
                new KeyValuePair<string, string>("Fiji Standard Time","FJ"),
                new KeyValuePair<string, string>("Kamchatka Standard Time","RU"),
                new KeyValuePair<string, string>("Tonga Standard Time","KI"),
                new KeyValuePair<string, string>("Samoa Standard Time","WS"),
                new KeyValuePair<string, string>("Line Islands Standard Time","WS"),
                };
                return _timezoneAndCountryList;
            }
        }
    }
}
