//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBZ.DAL.BankAdmin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DCBankAdminContext : DbContext
    {
        public DCBankAdminContext()
            : base("name=DCBankAdminContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BranchOfBank> BranchOfBanks { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<PrinterInformation> PrinterInformations { get; set; }
        public virtual DbSet<Requisition> Requisitions { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<UserInformation> UserInformations { get; set; }
    }
}
