//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBZ.DAL.BankAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        public long Id { get; set; }
        public string AccountNumber { get; set; }
        public string CustomerName { get; set; }
        public string ChequeBranch { get; set; }
        public string Cheque_location_code_RequestBranch_Code { get; set; }
        public string Location { get; set; }
        public string RequestBranchCode { get; set; }
        public Nullable<long> PickupBranchId { get; set; }
        public string SerialNumberStart { get; set; }
        public string ChequeBookType { get; set; }
        public Nullable<int> NumberOfLeaf { get; set; }
        public Nullable<long> PrinterId { get; set; }
        public string RequsitionSlipSerialNumber { get; set; }
        public string NRCPerson { get; set; }
        public string Status { get; set; }
        public string SerialNoOfCheqEnd { get; set; }
        public string DeliveredBy { get; set; }
        public Nullable<int> ChequeOrderBy { get; set; }
        public Nullable<int> ChequePrintedCommandBy { get; set; }
        public Nullable<System.DateTime> OrderDateTime { get; set; }
        public Nullable<System.DateTime> PrintDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
